--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-08-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBERS
--------------------------------------------------------

  CREATE TABLE "YOUNGYOUNG"."MEMBERS" 
   (	"MEM_ID" VARCHAR2(20 BYTE), 
	"MEM_PWD" VARCHAR2(30 BYTE), 
	"MEM_NAME" VARCHAR2(15 BYTE), 
	"MEM_BIRTHDAY" VARCHAR2(11 BYTE), 
	"MEM_NICKNAME" VARCHAR2(30 BYTE), 
	"MEM_PHONE_NUM" VARCHAR2(11 BYTE), 
	"MEM_BALANCE" NUMBER(7,0), 
	"MEM_PROFILE_IMG" VARCHAR2(500 BYTE), 
	"MEM_STATUS_MESSAGE" VARCHAR2(100 BYTE), 
	"MEM_STATUS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into YOUNGYOUNG.MEMBERS
SET DEFINE OFF;
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('seongbong','seongbong','노성봉','1994-10-09','노성봉','01050674188',0,'mem_img/seongbong_img.png','고독하구만',1);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('soyoung','soyoung','이소영','1993-06-04','이소영이','01083991901',0,'mem_img/soyoung_img.png','우리집에서 2차 고?',1);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('sooin','sooin','온수인','1992-09-04','온수인','01037399294',0,'mem_img/sooin_img.png','싫어',1);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('youngyoung','youngyoung','김태영','1999-01-22','김태영','01020612490',0,'mem_img/youngyoung_img.png','정확해요',1);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('sumin','sumin','김수민','1997-07-23','김수민','01051158823',0,'mem_img/sumin_img.png','서운해',1);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('jihoon','jihoon','원지훈','1995-01-07','원지훈','01088849517',0,'mem_img/jihoon_img.png','억울해',1);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('boram','boram','김보람','1991-01-01','김보람','01047557015',0,'mem_img/boram_img.png','민트초코',1);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('yeman','yeman','최예만','1994-01-01','최예만','01012341234',0,'mem_img/yeman_img.png','-',1);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('heonmyeong','heonmyeong','최헌명','1990-01-01','최헌명','01012345678',0,'mem_img/heonmyeong_img.png','반장님',1);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('jonghyeok','jonghyeok','한종혁','1992-01-01','한종혁','01087654321',0,'mem_img/jonghyeok_img.png','-',1);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('aran','aran','박아란','1994-03-15','귀염뽀짝','01071011416',60000,'mem_img/aran_img.png','귀여워 온수인',1);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('ym','123','최예멘','2021-03-03','야만','01000000000',900000,'mem_img/ym_img.png','반갑습니다',0);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('Taeyoung_kkk','12345','ㄱㄴㄷ','1991-06-13','올ㅋ','01079798282',40000,'mem_img/Taeyoung_kkk_img.jpg','My Way',0);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('Don','123','Don','1994-01-22','Don','01012345678',50000,'mem_img/Don_img.jpg','졸려~~',0);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('goems','goems','goems','2021-03-01','goems','01065505747',10000,'mem_img/goems_img.jpg','test',0);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('wooilds1','12345','김태영','2021-11-26','1조화이팅','01022233333',1970000,'mem_img/wooilds1_img.png','ㅎㅇ',0);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('ㅇㅇㅇ','123','탈랄라','0001-01-01','ㅋ','01112341234',980000,'mem_img/ㅇㅇㅇ_img.jpg',null,0);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('dkssud27','dlrco12#','조익호','1989-01-22','이코보코','01091907222',480000,'mem_img/dkssud27_img.jpg','테스트입니다',0);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('ddd','ddd','ddd','2021-03-03','ddd','33333333',990000,'mem_img/ddd_img.png','ddd',0);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('idid','12345','이름','2020-01-01','안녕','01011111111',970000,'mem_img/idid_img.jpg','ㅁㅅㅁ',0);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('remy','1234','remy','2020-07-29','bon','01012345678',0,'mem_img/remy_img.PNG','get all night',0);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('test5','test5','test5','2021-02-10','test5','0101234123',10000,'mem_img/test5_img.jpg','하이하이',0);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('canyi','123','ㅇㅇ','2021-03-02','표우','01078945612',980000,'mem_img/canyi_img.jpg','안녕! 나의 이름은 표우!',0);
Insert into YOUNGYOUNG.MEMBERS (MEM_ID,MEM_PWD,MEM_NAME,MEM_BIRTHDAY,MEM_NICKNAME,MEM_PHONE_NUM,MEM_BALANCE,MEM_PROFILE_IMG,MEM_STATUS_MESSAGE,MEM_STATUS) values ('allen','1234','allen','2021-03-08','allen','01012345678',20000,'mem_img/allen_img.png','1234',0);
--------------------------------------------------------
--  DDL for Index MEMBERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUNGYOUNG"."MEMBERS_PK" ON "YOUNGYOUNG"."MEMBERS" ("MEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBERS
--------------------------------------------------------

  ALTER TABLE "YOUNGYOUNG"."MEMBERS" MODIFY ("MEM_NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "YOUNGYOUNG"."MEMBERS" ADD CONSTRAINT "MEMBERS_PK" PRIMARY KEY ("MEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOUNGYOUNG"."MEMBERS" MODIFY ("MEM_PHONE_NUM" NOT NULL ENABLE);
  ALTER TABLE "YOUNGYOUNG"."MEMBERS" MODIFY ("MEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "YOUNGYOUNG"."MEMBERS" MODIFY ("MEM_PWD" NOT NULL ENABLE);
