--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-08-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SIGN_TOGETHER
--------------------------------------------------------

  CREATE TABLE "YOUNGYOUNG"."SIGN_TOGETHER" 
   (	"SIGN_NO" NUMBER(5,0), 
	"TOG_NO" VARCHAR2(8 BYTE), 
	"MEM_ID" VARCHAR2(20 BYTE), 
	"SIGN_TOTAL_ACHV" NUMBER(2,0), 
	"SIGN_ACHV" NUMBER(2,0), 
	"SIGN_STATUS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into YOUNGYOUNG.SIGN_TOGETHER
SET DEFINE OFF;
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (1,'100-1','soyoung',12,0,0);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (2,'100-1','sooin',12,0,0);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (3,'200-1','youngyoung',8,24,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (4,'200-1','yeman',8,24,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (5,'500-1','aran',10,9,1);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (6,'500-1','sooin',10,9,1);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (7,'300-1','sooin',6,18,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (8,'300-1','jihoon',6,18,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (9,'300-1','jonghyeok',6,18,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (10,'300-1','heonmyeong',6,18,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (11,'300-2','sooin',4,12,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (12,'300-2','seongbong',4,9,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (13,'300-2','soyoung',4,12,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (14,'300-3','sooin',4,6,1);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (15,'300-3','sumin',4,3,1);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (16,'300-3','youngyoung',4,3,1);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (17,'300-3','jihoon',4,6,1);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (18,'400-1','sooin',12,0,0);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (19,'600-1','yeman',6,0,0);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (20,'600-1','sooin',6,0,0);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (21,'600-1','seongbong',6,0,0);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (22,'700-1','jonghyeok',8,24,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (23,'700-1','sooin',8,24,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (24,'700-1','sumin',8,21,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (25,'700-1','jihoon',8,24,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (26,'700-2','jonghyeok',8,24,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (27,'700-3','jonghyeok',8,24,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (28,'700-3','youngyoung',8,24,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (29,'700-3','soyoung',8,24,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (30,'700-3','aran',8,24,2);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (31,'800-1','heonmyeong',6,3,1);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (32,'800-1','sooin',6,3,1);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (33,'900-1','sumin',10,0,0);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (34,'1000-1','jihoon',2,3,1);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (35,'1000-1','sooin',2,3,1);
Insert into YOUNGYOUNG.SIGN_TOGETHER (SIGN_NO,TOG_NO,MEM_ID,SIGN_TOTAL_ACHV,SIGN_ACHV,SIGN_STATUS) values (36,'1100-1','jihoon',10,0,0);
--------------------------------------------------------
--  DDL for Index TOGETHER_SIGN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUNGYOUNG"."TOGETHER_SIGN_PK" ON "YOUNGYOUNG"."SIGN_TOGETHER" ("SIGN_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_TOGETHER_PEOPLE_MINUS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "YOUNGYOUNG"."TRG_TOGETHER_PEOPLE_MINUS" 
after delete on sign_together
for each row
begin
update together set tog_people = tog_people-1 where tog_no = :old.tog_no;
update together set tog_sum = tog_sum-10000 where tog_no = :old.tog_no;
end;
/
ALTER TRIGGER "YOUNGYOUNG"."TRG_TOGETHER_PEOPLE_MINUS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TOGETHER_PEOPLE_PLUS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "YOUNGYOUNG"."TRG_TOGETHER_PEOPLE_PLUS" 
after insert on sign_together
for each row
begin
update together set tog_people = tog_people+1 where tog_no = :new.tog_no;
update together set tog_sum = tog_sum+10000 where tog_no = :new.tog_no;
end;
/
ALTER TRIGGER "YOUNGYOUNG"."TRG_TOGETHER_PEOPLE_PLUS" ENABLE;
--------------------------------------------------------
--  Constraints for Table SIGN_TOGETHER
--------------------------------------------------------

  ALTER TABLE "YOUNGYOUNG"."SIGN_TOGETHER" ADD CONSTRAINT "TOGETHER_SIGN_PK" PRIMARY KEY ("SIGN_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIGN_TOGETHER
--------------------------------------------------------

  ALTER TABLE "YOUNGYOUNG"."SIGN_TOGETHER" ADD CONSTRAINT "SIGN_MEMBER_FK" FOREIGN KEY ("MEM_ID")
	  REFERENCES "YOUNGYOUNG"."MEMBERS" ("MEM_ID") ENABLE;
  ALTER TABLE "YOUNGYOUNG"."SIGN_TOGETHER" ADD CONSTRAINT "SIGN_TOGETHER_FK" FOREIGN KEY ("TOG_NO")
	  REFERENCES "YOUNGYOUNG"."TOGETHER" ("TOG_NO") ENABLE;
